[versions]
agp = "8.4.1" # 8.3.0 causes java verifier error: https://github.com/ReVanced/revanced-patches/issues/2818
kotlin = "1.9.22"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
